### ISSUE TITLE
pip install -r requirements (There is no requirements file in the repo)

### ISSUE THREAD

**Issue by KrishPatel13** [MLDSAI/puterbot#1]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/65433817/231562889-e8f44bbe-16e8-419a-b2ba-95094d00634a.png">

I have successfully installed wheel package. Moving on the next command for setup, that is, 

`pip install -r requirements`

I found that there is no requirements file so that it could install the required libraries/packages.

Please guide me over it.

**Comment by jesicasusanto** [comment]
Yes I am also having issue with this step of the setup.

**Comment by abrichr** [comment]
Thank you! Fixed in https://github.com/MLDSAI/puterbot/commit/3e531fc68f67b32b26e74b76993fb88aab5ad934
