### ISSUE TITLE
Error in importing models module

### ISSUE THREAD

**Issue by KrishPatel13** [MLDSAI/puterbot#11]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/65433817/232506628-3be150d2-16a6-4dbd-be71-42eb451a4e06.png">

I want to import models to have the access to the `InputEvent` object. Please let me know if this is how we have import or InputEvent.

Another way i can think of is creating namedTuple as seen record.py as well:
```python
from typing import List
from collections import namedtuple

InputEvent = namedtuple('InputEvent', ['type', 'properties'])
Screenshot = namedtuple('Screenshot', ['png_data'])
WindowEvent = namedtuple('WindowEvent', ['type', 'properties'])
```

Please guide me. Thank you.

**Comment by abrichr** [comment]
Hi @KrishPatel13 ,

Try This:

```
from puterbot.models import InputEvent
```

**Comment by abrichr** [comment]
@KrishPatel13 please have a look at the updated instructions in the README: https://github.com/MLDSAI/puterbot/tree/main#instructions

**Comment by abrichr** [comment]
Hi @KrishPatel13 , were you able to resolve the issue you described at the top of this thread?

**Comment by KrishPatel13** [comment]
Yes, I was able to resolve it.
