### ISSUE TITLE
Confused on take_screenshot method in models.py

### ISSUE THREAD

**Issue by FFFiend** [MLDSAI/puterbot#34]
```
    def take_screenshot(cls):
        sct_img = take_screenshot()
        screenshot = Screenshot(sct_img=sct_img)
        return screenshot
```

In these lines (208-211) in Models.py, I'm confused on how this method works since there seems to be no base case ( as we call take_screenshot in the very first line ). I also checked the Base class in db.py to ensure if there was no method with the same name being inherited but this didn't seem to be the case.  Just wondering how this works :D

**Comment by 0dm** [comment]
Hey @FFFiend,

`take_screenshot(cls)` is a class method (cls), the first line is calling [`take_screenshot` from puterbot.utils](https://github.com/MLDSAI/puterbot/blob/02cfb5a007a7b4241a1bcb8a01bb0caeae618564/puterbot/utils.py#L366):
```py
def take_screenshot() -> mss.base.ScreenShot:
    with mss.mss() as sct:
        # monitor 0 is all in one
        monitor = sct.monitors[0]
        sct_img = sct.grab(monitor)
    return sct_img
```

**Comment by FFFiend** [comment]
ah okay, thanks :D
