### ISSUE TITLE
alembic upgrade head setup

### ISSUE THREAD

**Issue by jesicasusanto** [MLDSAI/puterbot#8]
I encountered an error message while attempting to complete the last setup step for PuterBot, which involves running the command "alembic upgrade head". The error message indicated that Alembic could not locate its configuration file named "alembic.ini"
<img width="500" alt="image" src="https://user-images.githubusercontent.com/87709055/232161216-d0184e3d-0eda-4146-a3aa-63fbd8192f7f.png">

Steps to reproduce : same as puterbot setup.

However, I found the "alembic.ini" file in the PAT directory, so I tried moving to that directory and running the "alembic upgrade head" command again. This time, the command ran without error.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/87709055/232162566-a9089850-5460-414f-b333-9a70e089d8c4.png">

I would like to confirm whether it is acceptable to perform the setup for PuterBot by moving to the PAT directory first before running the "alembic upgrade head" command. Thank you!

**Comment by abrichr** [comment]
Hi @jesicasusanto, thank you for reporting this. Changing directories is an acceptable workaround. We will fix the README accordingly.

Thanks again!
